# Generated by Django 5.2.7 on 2025-10-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
